"""initial_migration

Revision ID: 96488105820a
Revises: 
Create Date: 2026-02-10 15:55:11.113229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96488105820a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_feedback_decision_id'), 'decision_feedback', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_feedback_operator_id'), 'decision_feedback', ['operator_id'], unique=False)
    op.create_index('ix_feedback_decision_operator', 'decision_feedback', ['decision_id', 'operator_id'], unique=True)
    op.drop_index(op.f('ix_entity_relationships_relationship_type'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_tenant_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_relationships_source'), table_name='entity_relationships')
    op.drop_index(op.f('ix_relationships_target'), table_name='entity_relationships')
    op.drop_index(op.f('ix_relationships_type'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_network_entities_entity_type'), table_name='network_entities')
    op.drop_index(op.f('ix_network_entities_external'), table_name='network_entities')
    op.drop_index(op.f('ix_network_entities_external_id'), table_name='network_entities')
    op.drop_index(op.f('ix_network_entities_tenant_id'), table_name='network_entities')
    op.drop_index(op.f('ix_network_entities_tenant_type'), table_name='network_entities')
    op.drop_table('network_entities')
    op.add_column('decision_traces', sa.Column('ack_state', sa.String(length=50), nullable=False))
    op.add_column('decision_traces', sa.Column('external_correlation_id', sa.String(length=255), nullable=True))
    op.add_column('decision_traces', sa.Column('internal_correlation_id', sa.String(length=255), nullable=True))
    op.add_column('decision_traces', sa.Column('probable_cause', sa.String(length=100), nullable=True))
    op.add_column('decision_traces', sa.Column('feedback_score', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_kpi_metrics_entity_id'), table_name='kpi_metrics')
    op.drop_index(op.f('ix_kpi_metrics_entity_metric_time'), table_name='kpi_metrics')
    op.drop_index(op.f('ix_kpi_metrics_metric_name'), table_name='kpi_metrics')
    op.drop_index(op.f('ix_kpi_metrics_tenant_id'), table_name='kpi_metrics')
    op.drop_index(op.f('ix_kpi_metrics_tenant_time'), table_name='kpi_metrics')
    op.drop_column('kpi_metrics', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_metrics', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_kpi_metrics_tenant_time'), 'kpi_metrics', ['tenant_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_kpi_metrics_tenant_id'), 'kpi_metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_kpi_metrics_metric_name'), 'kpi_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_kpi_metrics_entity_metric_time'), 'kpi_metrics', ['entity_id', 'metric_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_kpi_metrics_entity_id'), 'kpi_metrics', ['entity_id'], unique=False)
    op.drop_column('decision_traces', 'feedback_score')
    op.drop_column('decision_traces', 'probable_cause')
    op.drop_column('decision_traces', 'internal_correlation_id')
    op.drop_column('decision_traces', 'external_correlation_id')
    op.drop_column('decision_traces', 'ack_state')
    op.create_table('network_entities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('operational_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('network_entities_pkey'))
    )
    op.create_index(op.f('ix_network_entities_tenant_type'), 'network_entities', ['tenant_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_network_entities_tenant_id'), 'network_entities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_network_entities_external_id'), 'network_entities', ['external_id'], unique=False)
    op.create_index(op.f('ix_network_entities_external'), 'network_entities', ['tenant_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_network_entities_entity_type'), 'network_entities', ['entity_type'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_entity_id'], ['network_entities.id'], name=op.f('entity_relationships_source_entity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['network_entities.id'], name=op.f('entity_relationships_target_entity_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_relationships_pkey'))
    )
    op.create_index(op.f('ix_relationships_type'), 'entity_relationships', ['tenant_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_target'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_source'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_tenant_id'), 'entity_relationships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_relationship_type'), 'entity_relationships', ['relationship_type'], unique=False)
    op.drop_index('ix_feedback_decision_operator', table_name='decision_feedback')
    op.drop_index(op.f('ix_decision_feedback_operator_id'), table_name='decision_feedback')
    op.drop_index(op.f('ix_decision_feedback_decision_id'), table_name='decision_feedback')
    op.drop_table('decision_feedback')
    # ### end Alembic commands ###
